### ISSUE TITLE
Feature Request - Sign Systemd-boot too

### ISSUE THREAD

**Issue by GHM-0** [berglh/ubuntu-sb-kernel-signing#19] opened 2024-08-12 15:30 UTC
It's not an issue, sorry about that. I'm just trying to sign systemd-boot, as I already did with grub, because systemd-boot is really fast, and I think that's the purpose of your software."

**Comment by berglh** [comment] 2024-08-13 11:43
systemd-boot is a bootloader and not a kernel image. systemd-boot as you pointed out replaces the grub bootloader. 

I'm not familiar with systemd-boot bootloader, but as I would understand it, if it were correctly configured, the issue is getting systemd-boot to work with Secure Boot enabled. The bootloader is the first bit of code launched from your storage device which then discovers Linux kernel images to boot. As long as you're still signing your kernel image that isn't already signed by Canonical/Ubuntu with this repository, then it should still function the same way.

If you're experiencing problems with systemd-boot booting a Linux kernel that's been signed with a Machine Owner Key (MOK) certificate that was enrolled into your EFI key store correctly, then that will be specifically be an issue with systemd-boot working with Secure Boot - likely the EFI image hasn't been signed with a key enrolled in your system motherboard EFI/BIOS.

My advice would be to use a standard Ubuntu kernel in the mean time as these are already correctly signed, and resolve whatever problems you're experiencing with the systemd-boot and get it working with Secure Boot enabled.

I'm assuming that systemd-boot will be an EFI file that will reside in the /boot partition of your Ubuntu system, if your BIOS is failing to load that EFI image for some reason, you'll need to look more into the debugging and support of systemd-boot as I'm not at all familiar with that.

If what you're wanting to do is sign the EFI image with a Machine Owner Key, this script isn't really designed to do that as it stands.

The actual command that signs the kernel image is here: https://github.com/berglh/ubuntu-sb-kernel-signing/blob/main/sbin/zz-signing#L46

If you have created a machine owner key with the default settings in the scripts in this repository, theoretically, you should able to do something like the following to sign an EFI bootloader image. **Note**: You'll need to do this as the root user.

```bash
EFI_IMAGE="/boot/efi/EFI/systemd/systemd-bootx64.efi"  # You will need to figure out if this is the correct file location for systemd-boot EFI
EFI_IMAGE_SIGNED="/boot/EFI/systemd/systemd-bootx-signed64.efi" # Change this to your desired output
MOK_CERT_NAME="MOK-Kernel"
MOK_DIRECTORY="/var/lib/shim-signed/mok"

sbsign --key "$MOK_DIRECTORY/$MOK_CERT_NAME.priv" --cert "$MOK_DIRECTORY/$MOK_CERT_NAME.pem" --output "$EFI_IMAGE_SIGNED" "$EFI_IMAGE"     # Will sign the bootloader with your machine owner key
```

The critical thing with this though is I'm unsure on the whether the `extendUsage` code in the certificate is correct, but initial looking online here seems to indicate it should work: https://ubuntu.com/blog/how-to-sign-things-for-secure-boot.

After you sign the EFI bootloader, you'll need to figure out how to put it in the right location.  For the grub signed image, on Ubuntu 24.04, you need to replace the `/boot/efi/EFI/BOOT/BOOTX64.EFI` with the signed `systemd-bootx-signed64.efi` file, this is the default EFI image location that is booted from a Ubuntu installation.

You might want to backup the BOOTX64.EFI image first, so that you can revert back to your existing bootloader.

I hope this makes sense. I'd recommend seeking support on `systemd-boot` as I mentioned I don't really know anything about it other than it's an alternative bootloader. The method that this automatic signing script uses to sign Ubuntu kernel images should work with any boot loader, so long as that boot loader is capable of working with Secure Boot and is signed with a key that's enrolled in your EFI (MOK list) key store.

I'm going to close this issue as it's not specifically related to this repository and is a `systemd-boot` process with Secure Boot, but I hope that gives you some idea of what you might need to be doing.

**Comment by berglh** [comment] 2024-08-13 11:48
Closing as out of scope for this project.

**Comment by berglh** [comment] 2024-08-13 11:48
Closing as out of scope for this project.

**Closed as not planned by berglh** 2024-08-13 11:48 UTC
